# Generated by Django 3.2.8 on 2024-08-06 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='reportes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('tipo_reporte', models.CharField(choices=[('preventivo', 'Preventivo'), ('reparacion', 'Reparación'), ('correctivo', 'Correctivo'), ('inspeccion_norma', 'Inspección Norma')], default='preventivo', max_length=20)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_see_reports', 'Can see reporte'), ('can_upload_reports', 'Can upload reporte')],
            },
        ),
    ]
