# Generated by Django 3.2.8 on 2024-08-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0004_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellido', 'nombre'], 'permissions': [('can_see_empleados', 'Can see empleados')], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
