# Generated by Django 3.2.8 on 2024-08-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0005_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
