# Generated by Django 4.2.5 on 2023-10-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_pendingmsgview_delete_mensajesmovil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingmsgview',
            name='cliente',
        ),
        migrations.AddField(
            model_name='pendingmsgview',
            name='to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
