# Generated by Django 4.2.5 on 2023-10-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_clienteprofile_company'),
        ('common', '0004_remove_pendingmsgview_cliente_pendingmsgview_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingmsgview',
            name='creado_por',
        ),
        migrations.AddField(
            model_name='pendingmsgview',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.clienteprofile'),
        ),
    ]
