# Generated by Django 3.2.8 on 2024-08-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_pendingmsgview_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colombiacities',
            name='department',
        ),
    ]
