# Generated by Django 4.2.5 on 2023-10-13 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, max_length=500)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('total_transaccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_fiado', models.BooleanField(default=False)),
                ('tipo_transaccion', models.CharField(choices=[('venta', 'Venta'), ('pago', 'Pago')], max_length=5)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.clienteprofile')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
