# Generated by Django 4.2.5 on 2023-10-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_alter_transaccion_tipo_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
