# Generated by Django 4.2.5 on 2023-10-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_alter_transaccion_observaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='usuario',
            new_name='creada_por',
        ),
    ]
