# Generated by Django 3.2.8 on 2024-04-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_rename_usuario_transaccion_creada_por'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'permissions': [('can_see_cliente_transacciones', 'Puede ver transacciones del cliente')], 'verbose_name': 'Transaccion', 'verbose_name_plural': 'Transacciones'},
        ),
    ]
