# Generated by Django 3.2.8 on 2024-04-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0005_alter_transaccion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'permissions': [('can_see_cliente_transacciones', 'Puede ver transacciones del cliente'), ('can_add_transaccion', 'Puede añadir transaccion'), ('can_edit_transaccion', 'Puede editar transaccion')], 'verbose_name': 'Transaccion', 'verbose_name_plural': 'Transacciones'},
        ),
    ]
