# Generated by Django 3.2.8 on 2024-06-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_clienteprofile_fin_fecha_membresia'),
        ('transacciones', '0006_alter_transaccion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_cliente', to='clientes.clienteprofile'),
        ),
    ]
