# Generated by Django 3.2.13 on 2023-10-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcompanyprofile',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical company profile'},
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
