# Generated by Django 3.2.8 on 2024-04-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='fin_fecha_membresia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompanyprofile',
            name='fin_fecha_membresia',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
