# Generated by Django 4.2.5 on 2023-10-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20231011_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcompanyprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical company profile', 'verbose_name_plural': 'historical company profiles'},
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
