# Generated by Django 3.2.8 on 2024-06-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20240619_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='companies/'),
        ),
        migrations.AddField(
            model_name='historicalcompanyprofile',
            name='profile_photo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
