# Generated by Django 3.2.8 on 2024-06-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_cierrecaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrecaja',
            name='total_credito',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='total_efectivo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='total_gastos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
