# Generated by Django 3.2.8 on 2024-06-29 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='companies.proprietario'),
        ),
        migrations.AddField(
            model_name='historicalcompanyprofile',
            name='propietario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.proprietario'),
        ),
    ]
