# Generated by Django 3.2.8 on 2024-07-01 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0008_auto_20240629_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalcompanyprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='users',
            field=models.ManyToManyField(related_name='company_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
