# Generated by Django 3.2.8 on 2024-07-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_companyprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_image_url',
            field=models.FileField(blank=True, null=True, upload_to='companies/'),
        ),
        migrations.AddField(
            model_name='historicalcompanyprofile',
            name='company_image_url',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
