# Generated by Django 3.2.8 on 2024-07-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_auto_20240725_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='company_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
