# Generated by Django 3.2.8 on 2024-07-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20240725_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='total_membresia',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='historicalcompanyprofile',
            name='total_membresia',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
