# Generated by Django 3.2.8 on 2024-08-05 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_pendingmsgview_data'),
        ('companies', '0014_auto_20240726_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.colombiacities'),
        ),
    ]
