# Generated by Django 4.2.5 on 2023-10-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_presentacion',
            field=models.CharField(blank=True, choices=[('kilo', 'Kilos'), ('libra', 'Libras'), ('gramos', 'Gramos'), ('galon', 'Galon'), ('litro', 'Litro'), ('cuarto litro', '1/4 Litro'), ('ml', 'ML'), ('unidad', 'Unidad'), ('metros', 'Metros'), ('centimetro', 'Centimetro')], max_length=100),
        ),
    ]
