# Generated by Django 4.2.5 on 2023-10-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_cantidad_producto_unidad_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_presentacion',
            field=models.CharField(blank=True, choices=[('kilo', 'KG'), ('libra', 'LB'), ('gramos', 'GRM'), ('galon', 'GL'), ('litro', 'LT'), ('cuarto litro', '1/4 LT'), ('ml', 'ML'), ('unidad', 'UND'), ('metros', 'MT'), ('centimetro', 'CM')], max_length=100),
        ),
    ]
