# Generated by Django 4.2.5 on 2023-10-24 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_unidad_presentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_presentacion',
        ),
    ]
