# Generated by Django 4.2.5 on 2023-10-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofile',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
