# Generated by Django 4.2.5 on 2023-10-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clienteprofile_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofile',
            name='credit_balance',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
