# Generated by Django 4.2.5 on 2023-10-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('clientes', '0003_clienteprofile_credit_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companyprofile'),
        ),
    ]
