# Generated by Django 3.2.8 on 2024-04-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_clienteprofile_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteprofile',
            options={'permissions': [('can_see_initial_view', 'Puede ver vista inicial')], 'verbose_name': 'Perfil de Clientes', 'verbose_name_plural': 'Perfiles de Clientes'},
        ),
    ]
