# Generated by Django 3.2.8 on 2024-04-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_clienteprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteprofile',
            options={'permissions': [('can_see_initial_view', 'Puede ver vista inicial'), ('can_see_clientes', 'Puede ver lista clientes'), ('can_create_cliente', 'Puede crear cliente'), ('can_ver_cliente', 'Puede ver detalle cliente'), ('can_edit_cliente', 'Puede editar cliente')], 'verbose_name': 'Perfil de Clientes', 'verbose_name_plural': 'Perfiles de Clientes'},
        ),
    ]
