# Generated by Django 3.2.8 on 2024-04-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('clientes', '0007_alter_clienteprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofile',
            name='fin_fecha_membresia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MembresiaEmpresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrada_el', models.DateTimeField(blank=True, null=True)),
                ('valor_pagado', models.PositiveIntegerField(blank=True, null=True)),
                ('dias_pagados', models.PositiveIntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companyprofile')),
            ],
        ),
    ]
