# Generated by Django 3.2.8 on 2024-04-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20240423_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteprofile',
            name='fin_fecha_membresia',
        ),
    ]
