# Generated by Django 3.2.8 on 2024-06-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_clienteprofile_fin_fecha_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteprofile',
            name='credit_balance',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
