# Generated by Django 3.2.8 on 2024-08-05 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20240726_0840'),
        ('gastos', '0002_alter_gasto_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companyprofile'),
        ),
    ]
